Logging:
  IncludeScopes: false
  LogLevel:
    Default: Information
    System: Information
    Microsoft: Information
    Fortune_Teller_Service: Debug
    Fortune_Teller_UI: Debug

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

#spring:
#  cloud:
#    services:
#      registrationMethod: direct

ribbon:
  IsSecure: false
