Logging:
  IncludeScopes: false
  LogLevel:
    Default: Information
    System: Information
    Microsoft: Information
    Fortune_Teller_Service: Debug
    Fortune_Teller_UI: Debug

eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

spring:
  cloud:
    services:
      registrationMethod: direct

ribbon:
  IsSecure: false
